name: Release
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
permissions:
  id-token: write
  contents: read
  packages: write
  security-events: write
  pull-requests: write

jobs:
  set-environment:
    name: Set Environment Type
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
    - name: Determine Environment Type
      id: set-env
      run: |
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          echo "environment=production" >> $GITHUB_ENV
          echo "::set-output name=environment::production"
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "environment=staging" >> $GITHUB_ENV
          echo "::set-output name=environment::staging"
        else
          echo "environment=development" >> $GITHUB_ENV
          echo "::set-output name=environment::development"
  build:
    name: Build and Lint
    uses: ./.github/workflows/development.yml

  docker:
    name: Docker
    uses: ./.github/workflows/docker.yml
    needs: [set-environment]
    environment: ${{ needs.set-environment.outputs.environment }}
    with:
      registry: ghcr.io
      image_name: joaquimscosta/costacodecraft-ui
  
  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-plan.yml
    needs: [docker]
    # if: needs.set-environment.outputs.environment == 'production'
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    with:
      docker_image: ${{ needs.docker.outputs.DOCKER_IMAGE }}
    secrets: inherit
  
  terraform-apply:
    name: Terraform Apply
    uses: ./.github/workflows/terraform-apply.yml
    needs: [docker, terraform-plan]
    with:
      docker_image: ${{ needs.docker.outputs.DOCKER_IMAGE }}
    secrets: inherit
 
