name: Release
on:
  push:
    tags:
      - 'v*'
    branches: ['refactor_workflows']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: joaquimscosta/costacodecraft-ui
  VERSION: 040319881
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Lint
    uses: ./.github/workflows/development.yml

  docker:
    name: Build Container
    needs: [build]
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write
      security-events: write
    outputs:
      DOCKER_IMAGE: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}
      
      - name: Build and Export image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          load: true
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{steps.meta.outcome.labels}}
          tags: |
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:latest
            ${{ steps.meta.outputs.tags }}

      - name: OCI image vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ steps.meta.outputs.tags }}
          fail-build: false
          severity-cutoff: high

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Publish container image
        run: |
          docker push ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:latest
          docker push ${{ steps.meta.outputs.tags }}
  deploy:
      name: Deploy
      needs: [docker]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Login to Azure
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          run: terraform init
          working-directory: ./terraform

        - name: Terraform Apply
          run: terraform apply -auto-approve
          working-directory: ./terraform