name: Release
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
permissions:
  id-token: write
  contents: read
  packages: write
  security-events: write
  pull-requests: write

jobs:
  build:
    name: Build and Lint
    uses: ./.github/workflows/development.yml

  docker:
    name: Docker
    uses: ./.github/workflows/docker.yml
    with:
      registry: ghcr.io
      image_name: joaquimscosta/costacodecraft-ui
  
  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-plan.yml
    needs: [docker]
    with:
      docker_image: ${{ needs.docker.outputs.DOCKER_IMAGE }}
    secrets: inherit
  
  terraform-apply:
    name: Terraform Apply
    uses: ./.github/workflows/terraform-apply.yml
    needs: [docker, terraform-plan]
    with:
      docker_image: ${{ needs.docker.outputs.DOCKER_IMAGE }}
    secrets: inherit
 
