name: Release
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: joaquimscosta/costacodecraft-ui
permissions:
  id-token: write

jobs:
  build:
    name: Build and Lint
    uses: ./.github/workflows/development.yml

  docker:
    name: Docker
    uses: ./.github/workflows/docker.yml
  
  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-plan.yml
    needs: [docker]
    with:
      docker_image: ${{ needs.docker.outputs.DOCKER_IMAGE }}
  
  terraform-apply:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-plan.yml
    needs: [docker, terraform-plan]
    with:
      docker_image: ${{ needs.docker.outputs.DOCKER_IMAGE }}
 