name: Release
on:
  push:
    tags:
      - "v*"
    branches: ["refactor_workflows"]
env:
  DOCKER_IMAGE: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}
  VERSION: 04031988
permissions:
  id-token: write
  contents: read

jobs:
  build: 
    name: Build and Lint
    uses: ./.github/workflows/development.yml

  docker:
    name: Build Container
    needs: [build]
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write
      security-events: write
    outputs:
      TAG: ${{ steps.fetch_version.outputs.TAG }}
    steps:
      - uses: actions/checkout@v3
      - name: Fetch latest version
        id: fetch_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          push: true
          tags: |
                ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:latest
                ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}:${{ env.VERSION }}